name: nsm_messenger
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core_platform_interface: ^5.0.0 
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.2
  cloud_firestore: ^4.13.5
  firebase_storage: ^11.5.5
  country_picker: ^2.0.15
  flutter_riverpod: ^2.0.0-dev.9
  image_picker: ^1.0.4
  flutter_contacts: ^1.1.5
  uuid: ^3.0.6
  intl: ^0.19.0
  cached_network_image: ^3.2.1
  cached_video_player: ^2.0.3
  emoji_picker_flutter: ^1.3.0
  enough_giphy_flutter: ^0.4.1
  flutter_sound: ^9.2.13
  path_provider: ^2.0.11
  permission_handler: ^11.1.0
  audioplayers: ^5.2.1
  swipe_to: ^1.0.2
  story_view: ^0.16.0
  agora_uikit: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/NSM.png

    