post_install do |installer|
    installer.pods_project.targets.each do |target|
        flutter_additional_ios_build_settings(target)
      # Start of the permission_handler configuration
      target.build_configurations.each do |config|
  
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
          '$(inherited)',

          # dart: PermissionGroup.microphone
          'PERMISSION_MICROPHONE=1',
        ]
  
      end
    end
  end